"""
JavaScript / TypeScript vulnerability detection rules
"""

JS_RULES = [
    {
        "id": "JS001",
        "name": "Eval Usage",
        "severity": "CRITICAL",
        "pattern": r"\beval\s*\(",
        "description": "eval() executes arbitrary JavaScript code.",
        "category": "Code Execution",
        "fix": "Remove eval(). Use JSON.parse() for data or refactor logic.",
    },
    {
        "id": "JS002",
        "name": "XSS via innerHTML",
        "severity": "HIGH",
        "pattern": r"\.innerHTML\s*=|\.outerHTML\s*=|document\.write\s*\(",
        "description": "Direct HTML injection can lead to XSS.",
        "category": "XSS",
        "fix": "Use textContent instead of innerHTML, or sanitize with DOMPurify.",
    },
    {
        "id": "JS003",
        "name": "Hardcoded Secret / API Key",
        "severity": "HIGH",
        "pattern": r"(password|secret|api_key|apiKey|token|passwd)\s*[:=]\s*[\"'][^\"']{4,}[\"']",
        "description": "Hardcoded credential or API key in source.",
        "category": "Secrets",
        "fix": "Use environment variables (process.env) or a secrets vault.",
    },
    {
        "id": "JS004",
        "name": "Prototype Pollution Risk",
        "severity": "HIGH",
        "pattern": r"__proto__|constructor\s*\[|prototype\s*\[",
        "description": "Possible prototype pollution vulnerability.",
        "category": "Injection",
        "fix": "Validate object keys. Use Object.create(null) for safe maps.",
    },
    {
        "id": "JS005",
        "name": "Insecure Random",
        "severity": "MEDIUM",
        "pattern": r"Math\.random\s*\(",
        "description": "Math.random() is not cryptographically secure.",
        "category": "Cryptography",
        "fix": "Use crypto.getRandomValues() or crypto.randomUUID() instead.",
    },
    {
        "id": "JS006",
        "name": "Node.js Child Process Injection",
        "severity": "CRITICAL",
        "pattern": r"(exec|execSync|spawn|spawnSync)\s*\(.*(\+|`|\$\{)",
        "description": "User-controlled data passed to shell command.",
        "category": "Injection",
        "fix": "Use execFile() with an argument array, avoid shell: true.",
    },
    {
        "id": "JS007",
        "name": "SQL Injection Risk",
        "severity": "CRITICAL",
        "pattern": r"(query|execute)\s*\([`\"'].*(\$\{|\+|%s)",
        "description": "String concatenation in SQL query.",
        "category": "Injection",
        "fix": "Use parameterized queries or an ORM.",
    },
    {
        "id": "JS008",
        "name": "Disabled HTTPS / SSL",
        "severity": "HIGH",
        "pattern": r"rejectUnauthorized\s*:\s*false|NODE_TLS_REJECT_UNAUTHORIZED\s*=\s*[\"']0[\"']",
        "description": "TLS certificate validation is disabled.",
        "category": "Cryptography",
        "fix": "Never disable TLS validation in production.",
    },
    {
        "id": "JS009",
        "name": "Weak JWT Algorithm",
        "severity": "HIGH",
        "pattern": r"algorithm[s]?\s*[:=]\s*[\"'](none|HS256)[\"']",
        "description": "Weak or disabled JWT algorithm.",
        "category": "Authentication",
        "fix": "Use RS256 or ES256. Never use 'none'.",
    },
    {
        "id": "JS010",
        "name": "console.log Sensitive Data",
        "severity": "LOW",
        "pattern": r"console\.(log|debug|info)\s*\(.*(password|token|secret|key|auth)",
        "description": "Sensitive data may be logged to console.",
        "category": "Information Disclosure",
        "fix": "Remove or mask sensitive data from logs.",
    },
]
